import { Type, FunctionDeclaration } from "@google/genai";

// --- i18n Translations ---
export const translations = {
    en: {
        title: 'Verbatim',
        subtitle: 'Your intelligent meeting dashboard.',
        welcomeUser: 'Welcome, {name}',
        startRecording: '🎤 New Session',
        stopRecording: '⏹️ Stop',
        analyzing: 'Analyzing...',
        processing: 'Processing...',
        micPermissionError: 'Could not start recording. Please grant microphone permissions.',
        processingError: 'Failed to process audio. This can happen due to a poor network connection, a very short recording, or if the audio is silent. Please try again.',
        offlineError: 'Analysis requires an internet connection. Please connect and try again.',
        recordingTooShortError: 'Recording is too short to analyze. Please record for at least 2 seconds.',
        transcriptHeader: '📋 Transcript',
        summaryHeader: '✨ Key Summary',
        actionItemsHeader: '📌 Action Items',
        noTranscript: 'Could not extract transcript.',
        noSummary: 'Could not extract summary.',
        noActionItems: 'No action items were identified.',
        takeAction: 'Take Action ✨',
        noActionDetermined: 'Could not determine a specific action for this item. You can handle it manually.',
        createCalendarEvent: 'Create Google Calendar Event',
        addToCalendar: 'Add to Calendar',
        titleLabel: 'Title:',
        descriptionLabel: 'Description:',
        dateLabel: 'Date:',
        timeLabel: 'Time:',
        openInGoogleCalendar: 'Open in Google Calendar',
        openInOutlookCalendar: 'Open in Outlook Calendar',
        draftEmail: 'Draft Email',
        toLabel: 'To:',
        subjectLabel: 'Subject:',
        bodyLabel: 'Body:',
        openInEmailApp: 'Open in Email App',
        draftInvoiceEmail: 'Draft Invoice Email',
        recipientNameLabel: 'Recipient Name:',
        amountLabel: 'Amount:',
        invoiceEmailBody: 'Hello {recipientName},\n\nThis is an invoice for the following item:\n- {itemDescription}\n\nAmount Due: {currencySymbol}{amount}\n\nPlease let me know if you have any questions.\n\nBest,\n{userName}',
        initiatePhoneCall: 'Initiate Phone Call',
        phoneNumberLabel: 'Phone Number:',
        reasonLabel: 'Reason:',
        callNow: 'Call Now',
        createDocument: 'Create Google Doc',
        createDocInfo: 'A new tab will open to create a Google Doc. The content below will be copied to your clipboard to paste.',
        suggestedTitle: 'Suggested Title:',
        suggestedContent: 'Suggested Content:',
        openGoogleDocs: 'Open Google Docs & Copy Content',
        unknownAction: 'Unknown Action',
        actionError: 'An error occurred while determining the action. Please try again.',
        exportResults: 'Export Results',
        copyMarkdown: 'Copy as Markdown',
        downloadMarkdown: 'Download as .md',
        copiedSuccess: 'Copied to clipboard!',
        meetingTitle: 'Meeting Notes',
        meetingLocation: 'Location:',
        locationUnavailable: 'Location not available',
        gettingLocation: 'Getting location...',
        speakersHeader: '🗣️ Speakers',
        renameSpeakerPrompt: 'Enter new name for',
        footerText: 'For Impactory Institute Use Only',
        recentSessions: 'Recent Sessions',
        welcomeMessage: 'Welcome to Verbatim',
        welcomeSubtext: 'Your recorded sessions will appear here. Tap the microphone to get started.',
        deleteSession: 'Delete Session?',
        deleteConfirmation: 'Are you sure you want to delete this session? This action cannot be undone.',
        searchPlaceholder: 'Search sessions...',
        toggleMiniView: 'Picture-in-Picture',
        keepAwake: 'Keep Screen Awake',
        keepAwakeInfo: 'Prevents the screen from turning off during a recording session.',
        backToList: 'Back to Sessions',
        recordPhoneCallTitle: 'Recording a Phone Call?',
        recordPhoneCallInstruction: 'For best quality, connect your headset. You can also use your phone\'s speaker. Tap the record button to begin.',
        selectAudioDeviceTitle: 'Select Audio Source',
        selectAudioDeviceInstruction: 'Choose the microphone you want to use for the recording.',
        start: 'Start',
        cancel: 'Cancel',
        analysisPrompt: 'You are an expert multilingual meeting assistant. The user\'s preferred language is English. Analyze the following meeting audio, which may contain multiple spoken languages. Your task is to process this multilingual audio and generate all output exclusively in English. Provide a concise summary, a list of action items, and a full transcript with speaker labels (e.g., Speaker 1, Speaker 2). In the summary, pay special attention to and clearly list any financial figures, budgets, or costs mentioned. Identify all unique speakers. All output text (summary, action items, transcript) MUST be translated to and written in English. Format the output as a JSON object with keys: "summary", "actionItems" (an array of strings), "transcript" (a string with newlines and speaker labels), and "speakers" (an array of identified speaker labels like ["Speaker 1", "Speaker 2"]). Do not include the JSON markdown wrapper.',
        actionPrompt: 'You are an intelligent assistant. Based on the full context of a meeting and a specific action item, call the most appropriate tool to help the user complete it. The user\'s language is English. Meeting Title: "{meetingTitle}". Meeting Date: "{meetingDate}". Meeting Summary: "{meetingSummary}". Action Item: "{actionItemText}". Ensure all generated content like email subjects or event descriptions are relevant to the meeting context.',
        sessions: 'Sessions',
        record: 'Record',
        recording: 'Recording...',
        tapToRecord: 'Tap to start recording',
        signIn: 'Sign In',
        signOut: 'Sign Out',
        signInToRecord: 'Sign in to start recording',
        signInToView: 'Sign in to view sessions',
        theme: 'Theme',
        language: 'Language',
        signInError: 'Failed to sign in with Google. Please try again.',
        signInPopupBlockedError: 'Sign-in popup was blocked by the browser. Please allow popups for this site.',
    },
    es: {
        title: 'Verbatim',
        subtitle: 'Tu panel de reuniones inteligente.',
        welcomeUser: 'Bienvenido, {name}',
        startRecording: '🎤 Nueva Sesión',
        stopRecording: '⏹️ Detener',
        analyzing: 'Analizando...',
        processing: 'Procesando...',
        micPermissionError: 'No se pudo iniciar la grabación. Por favor, concede permisos para el micrófono.',
        processingError: 'No se pudo procesar el audio. Esto puede ocurrir por una mala conexión de red, una grabación muy corta o si el audio está en silencio. Por favor, inténtalo de nuevo.',
        offlineError: 'El análisis requiere una conexión a internet. Por favor, conéctate y vuelve a intentarlo.',
        recordingTooShortError: 'La grabación es demasiado corta para analizar. Por favor, graba durante al menos 2 segundos.',
        transcriptHeader: '📋 Transcripción',
        summaryHeader: '✨ Resumen Clave',
        actionItemsHeader: '📌 Puntos de Acción',
        noTranscript: 'No se pudo extraer la transcripción.',
        noSummary: 'No se pudo extraer el resumen.',
        noActionItems: 'No se identificaron puntos de acción.',
        takeAction: 'Tomar Acción ✨',
        noActionDetermined: 'No se pudo determinar una acción específica para este ítem. Puedes gestionarlo manualmente.',
        createCalendarEvent: 'Crear Evento en Google Calendar',
        addToCalendar: 'Añadir al Calendario',
        titleLabel: 'Título:',
        descriptionLabel: 'Descripción:',
        dateLabel: 'Fecha:',
        timeLabel: 'Hora:',
        openInGoogleCalendar: 'Abrir en Google Calendar',
        openInOutlookCalendar: 'Abrir en Outlook Calendar',
        draftEmail: 'Redactar Correo',
        toLabel: 'Para:',
        subjectLabel: 'Asunto:',
        bodyLabel: 'Cuerpo:',
        openInEmailApp: 'Abrir en Correo',
        draftInvoiceEmail: 'Redactar Correo de Factura',
        recipientNameLabel: 'Nombre del Destinatario:',
        amountLabel: 'Monto:',
        invoiceEmailBody: 'Hola {recipientName},\n\nEsta es una factura para el siguiente artículo:\n- {itemDescription}\n\nMonto a pagar: {currencySymbol}{amount}\n\nSi tienes alguna pregunta, no dudes en contactarme.\n\nAtentamente,\n{userName}',
        initiatePhoneCall: 'Iniciar Llamada',
        phoneNumberLabel: 'Número de Teléfono:',
        reasonLabel: 'Motivo:',
        callNow: 'Llamar Ahora',
        createDocument: 'Crear Google Doc',
        createDocInfo: 'Se abrirá una nueva pestaña para crear un Google Doc. El contenido de abajo se copiará a tu portapapeles para que lo pegues.',
        suggestedTitle: 'Título Sugerido:',
        suggestedContent: 'Contenido Sugerido:',
        openGoogleDocs: 'Abrir Google Docs y Copiar Contenido',
        unknownAction: 'Acción Desconocida',
        actionError: 'Ocurrió un error al determinar la acción. Por favor, inténtalo de nuevo.',
        exportResults: 'Exportar Resultados',
        copyMarkdown: 'Copiar como Markdown',
        downloadMarkdown: 'Descargar como .md',
        copiedSuccess: '¡Copiado al portapapeles!',
        meetingTitle: 'Notas de la Reunión',
        meetingLocation: 'Ubicación:',
        locationUnavailable: 'Ubicación no disponible',
        gettingLocation: 'Obteniendo ubicación...',
        speakersHeader: '🗣️ Oradores',
        renameSpeakerPrompt: 'Ingrese el nuevo nombre para',
        footerText: 'Para Uso Exclusivo del Impactory Institute',
        recentSessions: 'Sesiones Recientes',
        welcomeMessage: 'Bienvenido a Verbatim',
        welcomeSubtext: 'Tus sesiones grabadas aparecerán aquí. Toca el micrófono para empezar.',
        deleteSession: '¿Eliminar Sesión?',
        deleteConfirmation: '¿Estás seguro de que quieres eliminar esta sesión? Esta acción no se puede deshacer.',
        searchPlaceholder: 'Buscar sesiones...',
        toggleMiniView: 'Picture-in-Picture',
        keepAwake: 'Mantener Pantalla Encendida',
        keepAwakeInfo: 'Evita que la pantalla se apague durante una sesión de grabación.',
        backToList: 'Volver a Sesiones',
        recordPhoneCallTitle: '¿Grabando una llamada telefónica?',
        recordPhoneCallInstruction: 'Para la mejor calidad, conecta tus auriculares. También puedes usar el altavoz de tu teléfono. Toca el botón de grabar para comenzar.',
        selectAudioDeviceTitle: 'Seleccionar Fuente de Audio',
        selectAudioDeviceInstruction: 'Elige el micrófono que deseas utilizar para la grabación.',
        start: 'Comenzar',
        cancel: 'Cancelar',
        analysisPrompt: 'Eres un experto asistente de reuniones multilingüe. El idioma preferido del usuario es español. Analiza el siguiente audio de la reunión, que puede contener varios idiomas hablados. Tu tarea es procesar este audio multilingüe y generar todo el resultado exclusivamente en español. Proporciona un resumen conciso, una lista de puntos de acción y una transcripción completa con etiquetas de orador (p. ej., Orador 1, Orador 2). En el resumen, presta especial atención y enumera claramente cualquier cifra financiera, presupuesto o costo mencionado. Identifica a todos los oradores únicos. Todo el texto de salida (resumen, puntos de acción, transcripción) DEBE ser traducido y escrito en español. Formatea la salida como un objeto JSON con las claves: "summary", "actionItems" (un array de strings), "transcript" (un string con saltos de línea y etiquetas de orador), y "speakers" (un array de etiquetas de orador identificadas como ["Orador 1", "Orador 2"]). No incluyas el envoltorio de markdown para JSON.',
        actionPrompt: 'Eres un asistente inteligente. Basado en el contexto completo de una reunión y un punto de acción específico, llama a la herramienta más apropiada para ayudar al usuario a completarlo. El idioma del usuario es español. Título de la reunión: "{meetingTitle}". Fecha de la reunión: "{meetingDate}". Resumen de la reunión: "{meetingSummary}". Punto de acción: "{actionItemText}". Asegúrate de que todo el contenido generado, como asuntos de correo o descripciones de eventos, sea relevante para el contexto de la reunión.',
        sessions: 'Sesiones',
        record: 'Grabar',
        recording: 'Grabando...',
        tapToRecord: 'Toca para empezar a grabar',
        signIn: 'Iniciar Sesión',
        signOut: 'Cerrar Sesión',
        signInToRecord: 'Inicia sesión para grabar',
        signInToView: 'Inicia sesión para ver sesiones',
        theme: 'Tema',
        language: 'Idioma',
        signInError: 'Error al iniciar sesión con Google. Por favor, inténtelo de nuevo.',
        signInPopupBlockedError: 'El navegador bloqueó la ventana de inicio de sesión. Por favor, permita las ventanas emergentes para este sitio.',
    },
    'zh-CN': {
        title: 'Verbatim',
        subtitle: '您的智能会议仪表板。',
        welcomeUser: '欢迎，{name}',
        startRecording: '🎤 新建会话',
        stopRecording: '⏹️ 停止',
        analyzing: '正在分析...',
        processing: '处理中...',
        micPermissionError: '无法开始录音。请授予麦克风权限。',
        processingError: '处理音频失败。这可能是由于网络连接不佳、录音时间过短或音频无声。请重试。',
        offlineError: '分析需要网络连接。请连接网络后重试。',
        recordingTooShortError: '录音时间太短，无法分析。请至少录制2秒。',
        transcriptHeader: '📋 文字记录',
        summaryHeader: '✨ 核心摘要',
        actionItemsHeader: '📌 行动项',
        noTranscript: '无法提取文字记录。',
        noSummary: '无法提取摘要。',
        noActionItems: '未识别出任何行动项。',
        takeAction: '执行操作 ✨',
        noActionDetermined: '无法为此项目确定具体操作。请手动处理。',
        createCalendarEvent: '创建谷歌日历活动',
        addToCalendar: '添加到日历',
        titleLabel: '标题:',
        descriptionLabel: '描述:',
        dateLabel: '日期:',
        timeLabel: '时间:',
        openInGoogleCalendar: '在谷歌日历中打开',
        openInOutlookCalendar: '在 Outlook 日历中打开',
        draftEmail: '草拟邮件',
        toLabel: '收件人:',
        subjectLabel: '主题:',
        bodyLabel: '正文:',
        openInEmailApp: '在邮件应用中打开',
        draftInvoiceEmail: '草拟发票邮件',
        recipientNameLabel: '收件人姓名:',
        amountLabel: '金额:',
        invoiceEmailBody: '您好 {recipientName}，\n\n这是关于以下项目的发票：\n- {itemDescription}\n\n应付金额：{currencySymbol}{amount}\n\n如果您有任何问题，请随时与我联系。\n\n此致，\n{userName}',
        initiatePhoneCall: '拨打电话',
        phoneNumberLabel: '电话号码:',
        reasonLabel: '呼叫原因:',
        callNow: '立即呼叫',
        createDocument: '创建谷歌文档',
        createDocInfo: '将打开一个新标签页来创建谷歌文档。下面的内容将被复制到您的剪贴板以便粘贴。',
        suggestedTitle: '建议标题:',
        suggestedContent: '建议内容:',
        openGoogleDocs: '打开谷歌文档并复制内容',
        unknownAction: '未知操作',
        actionError: '确定操作时发生错误。请重试。',
        exportResults: '导出结果',
        copyMarkdown: '复制为 Markdown',
        downloadMarkdown: '下载为 .md 文件',
        copiedSuccess: '已复制到剪贴板！',
        meetingTitle: '会议记录',
        meetingLocation: '地点:',
        locationUnavailable: '地点不可用',
        gettingLocation: '正在获取地点...',
        speakersHeader: '🗣️ 发言人',
        renameSpeakerPrompt: '输入新名称',
        footerText: '仅供 Impactory Institute 使用',
        recentSessions: '最近的会话',
        welcomeMessage: '欢迎使用 Verbatim',
        welcomeSubtext: '您录制的会话将显示在此处。点击麦克风即可开始。',
        deleteSession: '删除会话？',
        deleteConfirmation: '您确定要删除此会话吗？此操作无法撤销。',
        searchPlaceholder: '搜索会话...',
        toggleMiniView: '画中画',
        keepAwake: '保持屏幕常亮',
        keepAwakeInfo: '在录音期间防止屏幕关闭。',
        backToList: '返回会话列表',
        recordPhoneCallTitle: '正在录制电话通话？',
        recordPhoneCallInstruction: '为获得最佳音质，请连接您的耳机。您也可以使用手机的扬声器。点击录音按钮开始。',
        selectAudioDeviceTitle: '选择音频源',
        selectAudioDeviceInstruction: '请选择您要用于录音的麦克风。',
        start: '开始',
        cancel: '取消',
        analysisPrompt: '你是一位专业的多语言会议助理。用户的首选语言是简体中文。请分析接下来的会议音频，其中可能包含多种口语语言。你的任务是处理这段多语言音频，并仅以简体中文生成所有输出。请提供简明的摘要、行动项列表，以及带有发言人标签（例如，发言人1，发言人2）的完整文字记录。在摘要中，请特别注意并清晰地列出任何提及的财务数据、预算或成本。识别所有独立发言人。所有输出文本（摘要、行动项、文字记录）必须翻译成并以简体中文书写。将输出格式化为 JSON 对象，键为："summary"、"actionItems"（字符串数组）、"transcript"（带换行符和发言人标签的字符串），以及 "speakers"（已识别的发言人标签数组，如 ["发言人 1", "发言人 2"]）。不要包含 JSON 的 markdown 包装。',
        actionPrompt: '你是一个智能助理。请根据会议的完整背景和具体的行动项，调用最合适的工具来帮助用户完成它。用户的语言是简体中文。会议标题：“{meetingTitle}”。会议日期：“{meetingDate}”。会议摘要：“{meetingSummary}”。行动项：“{actionItemText}”。确保所有生成的内容（如邮件主题或活动描述）都与会议背景相关。',
        sessions: '会话',
        record: '录音',
        recording: '录音中...',
        tapToRecord: '点击开始录音',
        signIn: '登录',
        signOut: '登出',
        signInToRecord: '登录以开始录音',
        signInToView: '登录以查看会话',
        theme: '主题',
        language: '语言',
        signInError: 'Google 登录失败，请重试。',
        signInPopupBlockedError: '登录弹出窗口被浏览器阻止。请允许此站点的弹出窗口。',
    },
     'zh-TW': {
        title: 'Verbatim',
        subtitle: '您的智慧會議儀表板。',
        welcomeUser: '歡迎，{name}',
        startRecording: '🎤 新增會話',
        stopRecording: '⏹️ 停止',
        analyzing: '分析中...',
        processing: '處理中...',
        micPermissionError: '無法開始錄音。請授予麥克風權限。',
        processingError: '處理音訊失敗。這可能是由於網路連線不佳、錄音時間過短或音訊無聲。請重試。',
        offlineError: '分析需要網路連線。請連線後重試。',
        recordingTooShortError: '錄音時間太短，無法分析。請至少錄製2秒。',
        transcriptHeader: '📋 文字記錄',
        summaryHeader: '✨ 核心摘要',
        actionItemsHeader: '📌 行動項',
        noTranscript: '無法擷取文字記錄。',
        noSummary: '無法擷取摘要。',
        noActionItems: '未識別出任何行動項。',
        takeAction: '執行操作 ✨',
        noActionDetermined: '無法為此項目確定具體操作。請手動處理。',
        createCalendarEvent: '建立 Google 日曆活動',
        addToCalendar: '新增至日曆',
        titleLabel: '標題:',
        descriptionLabel: '描述:',
        dateLabel: '日期:',
        timeLabel: '時間:',
        openInGoogleCalendar: '在 Google 日曆中開啟',
        openInOutlookCalendar: '在 Outlook 日曆中開啟',
        draftEmail: '草擬郵件',
        toLabel: '收件人:',
        subjectLabel: '主旨:',
        bodyLabel: '內文:',
        openInEmailApp: '在郵件應用程式中開啟',
        draftInvoiceEmail: '草擬發票郵件',
        recipientNameLabel: '收件人姓名:',
        amountLabel: '金額:',
        invoiceEmailBody: '您好 {recipientName}，\n\n這是關於以下項目的發票：\n- {itemDescription}\n\n應付金額：{currencySymbol}{amount}\n\n如果您有任何問題，請隨時與我聯繫。\n\n此致，\n{userName}',
        initiatePhoneCall: '撥打電話',
        phoneNumberLabel: '電話號碼:',
        reasonLabel: '通話原因:',
        callNow: '立即通話',
        createDocument: '建立 Google 文件',
        createDocInfo: '將開啟一個新分頁來建立 Google 文件。下面的內容將被複製到您的剪貼簿以便貼上。',
        suggestedTitle: '建議標題:',
        suggestedContent: '建議內容:',
        openGoogleDocs: '開啟 Google 文件並複製內容',
        unknownAction: '未知操作',
        actionError: '確定操作時發生錯誤。請重試。',
        exportResults: '匯出結果',
        copyMarkdown: '複製為 Markdown',
        downloadMarkdown: '下載為 .md 檔案',
        copiedSuccess: '已複製到剪貼簿！',
        meetingTitle: '會議記錄',
        meetingLocation: '地點:',
        locationUnavailable: '地點不可用',
        gettingLocation: '正在取得地點...',
        speakersHeader: '🗣️ 發言人',
        renameSpeakerPrompt: '輸入新名稱',
        footerText: '僅供 Impactory Institute 使用',
        recentSessions: '最近的會話',
        welcomeMessage: '歡迎使用 Verbatim',
        welcomeSubtext: '您錄製的會話將顯示在此處。點擊麥克風即可開始。',
        deleteSession: '刪除會話？',
        deleteConfirmation: '您確定要刪除此會話嗎？此操作無法撤銷。',
        searchPlaceholder: '搜尋會話...',
        toggleMiniView: '子母畫面',
        keepAwake: '保持螢幕常亮',
        keepAwakeInfo: '在錄音期間防止螢幕關閉。',
        backToList: '返回會話列表',
        recordPhoneCallTitle: '正在錄製電話通話？',
        recordPhoneCallInstruction: '為獲得最佳音質，請連接您的耳機。您也可以使用手機的揚聲器。點擊錄音按鈕開始。',
        selectAudioDeviceTitle: '選取音訊來源',
        selectAudioDeviceInstruction: '請選擇您要用於錄音的麥克風。',
        start: '開始',
        cancel: '取消',
        analysisPrompt: '你是一位專業的多語言會議助理。使用者的首選語言是繁體中文。請分析接下來的會議音訊，其中可能包含多種口語語言。你的任務是處理這段多語言音訊，並僅以繁體中文產生所有輸出。請提供簡明的摘要、行動項列表，以及帶有發言人標籤（例如，發言人1，發言人2）的完整文字記錄。在摘要中，請特別注意並清晰地列出任何提及的財務數據、預算或成本。識別所有獨立發言人。所有輸出文字（摘要、行動項、文字記錄）必須翻譯成並以繁體中文書寫。將輸出格式化為 JSON 物件，鍵為："summary"、"actionItems"（字串陣列）、"transcript"（帶換行符和發言人標籤的字串），以及 "speakers"（已識別的發言人標籤陣列，如 ["發言人 1", "發言人 2"]）。不要包含 JSON 的 markdown 包裝。',
        actionPrompt: '你是一個智慧助理。請根據會議的完整背景和具體的行動項，呼叫最合適的工具來幫助使用者完成它。使用者的語言是繁體中文。會議標題：「{meetingTitle}」。會議日期：「{meetingDate}」。會議摘要：「{meetingSummary}」。行動項：「{actionItemText}」。確保所有生成的內容（如郵件主旨或活動描述）都與會議背景相關。',
        sessions: '會話',
        record: '錄製',
        recording: '錄製中...',
        tapToRecord: '點擊以開始錄製',
        signIn: '登入',
        signOut: '登出',
        signInToRecord: '登入以開始錄製',
        signInToView: '登入以查看會話',
        theme: '主題',
        language: '語言',
        signInError: 'Google 登入失敗，請重試。',
        signInPopupBlockedError: '登入彈出視窗被瀏覽器封鎖。請允許此網站的彈出視窗。',
    },
};

// --- Firebase Initialization ---
export const firebaseConfig = {
  apiKey: "AIzaSyBjEvuItFoeMQRo3K9poC179RayWSNGRsw",
  authDomain: "gen-lang-client-0046527508.firebaseapp.com",
  projectId: "gen-lang-client-0046527508",
  storageBucket: "gen-lang-client-0046527508.appspot.com",
  messagingSenderId: "842883143615",
  appId: "1:842883143615:web:21a6e14ca11e78df87730a",
  measurementId: "G-WR0SBSETLH"
};


// --- Gemini Function Calling Tool Definitions ---
export const tools: FunctionDeclaration[] = [
    { name: 'create_calendar_event', description: 'Creates a Google Calendar event.', parameters: { type: Type.OBJECT, properties: { title: { type: Type.STRING, description: 'The title of the event.' }, description: { type: Type.STRING, description: 'The description or agenda for the event.' }, date: { type: Type.STRING, description: 'The date of the event in YYYY-MM-DD format.' }, time: { type: Type.STRING, description: 'The time of the event in HH:MM format (24-hour).' } }, required: ['title', 'date', 'time'] } },
    { name: 'draft_email', description: 'Drafts an email to a recipient.', parameters: { type: Type.OBJECT, properties: { to: { type: Type.STRING, description: 'The recipient\'s email address.' }, subject: { type: Type.STRING, description: 'The subject line of the email.' }, body: { type: Type.STRING, description: 'The body content of the email.' } }, required: ['to', 'subject', 'body'] } },
    { name: 'draft_invoice_email', description: 'Drafts an email with an invoice for a client.', parameters: { type: Type.OBJECT, properties: { recipient_name: { type: Type.STRING, description: 'The name of the person or company receiving the invoice.' }, item_description: { type: Type.STRING, description: 'A description of the product or service being invoiced.' }, amount: { type: Type.NUMBER, description: 'The total amount due.' } }, required: ['recipient_name', 'item_description', 'amount'] } },
    { name: 'initiate_phone_call', description: 'Initiates a phone call.', parameters: { type: Type.OBJECT, properties: { phone_number: { type: Type.STRING, description: 'The phone number to call.' }, reason: { type: Type.STRING, description: 'A brief summary of why the call is being made.' } }, required: ['phone_number'] } },
    { name: 'create_google_doc', description: 'Creates a new Google Document with specified content.', parameters: { type: Type.OBJECT, properties: { title: { type: Type.STRING, description: 'The title of the document.' }, content: { type: Type.STRING, description: 'The initial content to be placed in the document.' } }, required: ['title', 'content'] } }
];
