mutation CreateNewTask($title: String!, $description: String, $dueDate: Timestamp!, $priority: String!, $status: String!) @auth(level: USER) {
  task_insert(data: {
    title: $title,
    description: $description,
    dueDate: $dueDate,
    priority: $priority,
    status: $status,
    userId_expr: "auth.uid"
  })
}

query GetMyTasks @auth(level: USER) {
  tasks(where: {userId: {eq_expr: "auth.uid"}}) {
    id
    title
    description
    dueDate
    priority
    status
  }
}

mutation UpdateTask($id: UUID!, $title: String, $description: String, $dueDate: Timestamp, $priority: String, $status: String) @auth(level: USER) {
  task_update(
    key: {id: $id}
    data: {
      title: $title
      description: $description
      dueDate: $dueDate
      priority: $priority
      status: $status
    }
  )
}

mutation DeleteTask($id: UUID!) @auth(level: USER) {
  task_delete(key: {id: $id})
}