type Query {
  listTodos: [Todo] @firebase(collection: "todos")
  getTodo(id: ID!): Todo @firebase(collection: "todos")
}

type Mutation {
  createTodo(title: String!): Todo @firebase(collection: "todos")
  updateTodo(id: ID!, title: String, completed: Boolean): Todo @firebase(collection: "todos")
  deleteTodo(id: ID!): Todo @firebase(collection: "todos")
}

type Todo @firebase(collection: "todos") {
  id: ID!
  title: String!
  completed: Boolean
}
